package com.qdu.pojo;
 




/**
 * Admin generated by hbm2java
 */
public class Admin  implements java.io.Serializable {

  
     private int id;
     private String pwd;

    public Admin() {
    }

    public Admin(int id, String pwd) {
       this.id = id;
       this.pwd = pwd;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getPwd() {
        return this.pwd;
    }
    
    public void setPwd(String pwd) {
        this.pwd = pwd;
    }




}


