package com.qdu.pojo;  
 




/**
 * Areas generated by hbm2java
 */
public class Areas  implements java.io.Serializable {


     private int rid;
     private String province;
     private String city;
     private String district;
     private int postCode;

    public Areas() {
    }

    public Areas(int rid, String province, String city, String district, int postCode) {
       this.rid = rid;
       this.province = province;
       this.city = city;
       this.district = district;
       this.postCode = postCode;
    }
   
    public int getRid() {
        return this.rid;
    }
    
    public void setRid(int rid) {
        this.rid = rid;
    }
    public String getProvince() {
        return this.province;
    }
    
    public void setProvince(String province) {
        this.province = province;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getDistrict() {
        return this.district;
    }
    
    public void setDistrict(String district) {
        this.district = district;
    }
    public int getPostCode() {
        return this.postCode;
    }
    
    public void setPostCode(int postCode) {
        this.postCode = postCode;
    }




}


