package com.qdu.pojo;  
 




/**
 * Departments generated by hbm2java
 */
public class Departments  implements java.io.Serializable {


     private int deId;
     private String edepartment;
     private String other;

    public Departments() {
    }

	
    public Departments(int deId) {
        this.deId = deId;
    }
    public Departments(int deId, String edepartment, String other) {
       this.deId = deId;
       this.edepartment = edepartment;
       this.other = other;
    }
   
    public int getDeId() {
        return this.deId;
    }
    
    public void setDeId(int deId) {
        this.deId = deId;
    }
    public String getEdepartment() {
        return this.edepartment;
    }
    
    public void setEdepartment(String edepartment) {
        this.edepartment = edepartment;
    }
    public String getOther() {
        return this.other;
    }
    
    public void setOther(String other) {
        this.other = other;
    }




}


