package com.qdu.pojo;  
 




/**
 * DiapatchBillInfo generated by hbm2java
 */
public class DiapatchBillInfo  implements java.io.Serializable {


     private int did;
     private String senderName;
     private String senderAddress;
     private String senderPhone;
     private String consigneeName;
     private String consigneeAddress;
     private String consigneePhone;
     private int number;
     private String other;

    public DiapatchBillInfo() {
    }

	
    public DiapatchBillInfo(int did) {
        this.did = did;
       
    }
    public DiapatchBillInfo(int did, String senderName, String senderAddress, String senderPhone, String consigneeName, String consigneeAddress, String consigneePhone, int number, String other) {
       this.did = did;
       this.senderName = senderName;
       this.senderAddress = senderAddress;
       this.senderPhone = senderPhone;
       this.consigneeName = consigneeName;
       this.consigneeAddress = consigneeAddress;
       this.consigneePhone = consigneePhone;
       this.number = number;
       this.other = other;
    }
   
    public int getDid() {
        return this.did;
    }
    
    public void setDid(int did) {
        this.did = did;
    }
    public String getSenderName() {
        return this.senderName;
    }
    
    public void setSenderName(String senderName) {
        this.senderName = senderName;
    }
    public String getSenderAddress() {
        return this.senderAddress;
    }
    
    public void setSenderAddress(String senderAddress) {
        this.senderAddress = senderAddress;
    }
    public String getSenderPhone() {
        return this.senderPhone;
    }
    
    public void setSenderPhone(String senderPhone) {
        this.senderPhone = senderPhone;
    }
    public String getConsigneeName() {
        return this.consigneeName;
    }
    
    public void setConsigneeName(String consigneeName) {
        this.consigneeName = consigneeName;
    }
    public String getConsigneeAddress() {
        return this.consigneeAddress;
    }
    
    public void setConsigneeAddress(String consigneeAddress) {
        this.consigneeAddress = consigneeAddress;
    }
    public String getConsigneePhone() {
        return this.consigneePhone;
    }
    
    public void setConsigneePhone(String consigneePhone) {
        this.consigneePhone = consigneePhone;
    }
    public int getNumber() {
        return this.number;
    }
    
    public void setNumber(int number) {
        this.number = number;
    }
    public String getOther() {
        return this.other;
    }
    
    public void setOther(String other) {
        this.other = other;
    }




}


