package com.qdu.pojo;  
 



import java.math.BigDecimal;

/**
 * EmployeesInfo generated by hbm2java
 */
public class EmployeesInfo  implements java.io.Serializable {


     private int eid;
     private String ename;
     private String epwd;
     private String equestion;
     private String eanswer;
     private String egender;
     private String edepartment;
     private String eoccupation;
     private String ephone;
     private String esalary;
     private String email;
     private Integer ekey;

    public EmployeesInfo() {
    }

	
    public EmployeesInfo(int eid) {
        this.eid = eid;
    }
    public EmployeesInfo(int eid, String ename, String epwd, String equestion, String eanswer, String egender, String edepartment, String eoccupation, String ephone, String esalary, String email, Integer ekey) {
       this.eid = eid;
       this.ename = ename;
       this.epwd = epwd;
       this.equestion = equestion;
       this.eanswer = eanswer;
       this.egender = egender;
       this.edepartment = edepartment;
       this.eoccupation = eoccupation;
       this.ephone = ephone;
       this.esalary = esalary;
       this.email = email;
       this.ekey = ekey;
    }
   
    public int getEid() {
        return this.eid;
    }
    
    public void setEid(int eid) {
        this.eid = eid;
    }
    public String getEname() {
        return this.ename;
    }
    
    public void setEname(String ename) {
        this.ename = ename;
    }
    public String getEpwd() {
        return this.epwd;
    }
    
    public void setEpwd(String epwd) {
        this.epwd = epwd;
    }
    public String getEquestion() {
        return this.equestion;
    }
    
    public void setEquestion(String equestion) {
        this.equestion = equestion;
    }
    public String getEanswer() {
        return this.eanswer;
    }
    
    public void setEanswer(String eanswer) {
        this.eanswer = eanswer;
    }
    public String getEgender() {
        return this.egender;
    }
    
    public void setEgender(String egender) {
        this.egender = egender;
    }
    public String getEdepartment() {
        return this.edepartment;
    }
    
    public void setEdepartment(String edepartment) {
        this.edepartment = edepartment;
    }
    public String getEoccupation() {
        return this.eoccupation;
    }
    
    public void setEoccupation(String eoccupation) {
        this.eoccupation = eoccupation;
    }
    public String getEphone() {
        return this.ephone;
    }
    
    public void setEphone(String ephone) {
        this.ephone = ephone;
    }
    public String getEsalary() {
        return this.esalary;
    }
    
    public void setEsalary(String esalary) {
        this.esalary = esalary;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Integer getEkey() {
        return this.ekey;
    }
    
    public void setEkey(Integer ekey) {
        this.ekey = ekey;
    }




}


