package com.qdu.pojo;  
 



/**
 * NormalBillInfo generated by hbm2java
 */
public class NormalBillInfo  implements java.io.Serializable {


     private int nid;
     private int did;
     private String other;
     private String pickupTime;

    public NormalBillInfo() {
    }

	
    public NormalBillInfo(int nid, int did, String pickupTime) {
        this.nid = nid;
        this.did = did;
        this.pickupTime = pickupTime;
    }
    public NormalBillInfo(int nid, int did, String other, String pickupTime) {
       this.nid = nid;
       this.did = did;
       this.other = other;
       this.pickupTime = pickupTime;
    }
   
    public int getNid() {
        return this.nid;
    }
    
    public void setNid(int nid) {
        this.nid = nid;
    }
    public int getDid() {
        return this.did;
    }
    
    public void setDid(int did) {
        this.did = did;
    }
    public String getOther() {
        return this.other;
    }
    
    public void setOther(String other) {
        this.other = other;
    }
    public String getPickupTime() {
        return this.pickupTime;
    }
    
    public void setPickupTime(String pickupTime) {
        this.pickupTime = pickupTime;
    }




}


