package com.qdu.pojo;
 




/**
 * Occupations generated by hbm2java
 */
public class Occupations  implements java.io.Serializable {


     private int oid;
     private String eoccupation;
     private String other;

    public Occupations() {
    }

	
    public Occupations(int oid) {
        this.oid = oid;
    }
    public Occupations(int oid, String eoccupation, String other) {
       this.oid = oid;
       this.eoccupation = eoccupation;
       this.other = other;
    }
   
    public int getOid() {
        return this.oid;
    }
    
    public void setOid(int oid) {
        this.oid = oid;
    }
    public String getEoccupation() {
        return this.eoccupation;
    }
    
    public void setEoccupation(String eoccupation) {
        this.eoccupation = eoccupation;
    }
    public String getOther() {
        return this.other;
    }
    
    public void setOther(String other) {
        this.other = other;
    }




}


