package com.qdu.pojo;
 





/**
 * Saff generated by hbm2java
 */
public class Saff  implements java.io.Serializable {


     private int sid;
     private String sname;
     private String sgender;
     private String sphone;
     private String semail;

    public Saff() {
    }

	
    public Saff(int sid) {
        this.sid = sid;
    }
    public Saff(int sid, String sname, String sgender, String sphone, String semail) {
       this.sid = sid;
       this.sname = sname;
       this.sgender = sgender;
       this.sphone = sphone;
       this.semail = semail;
    }
   
    public int getSid() {
        return this.sid;
    }
    
    public void setSid(int sid) {
        this.sid = sid;
    }
    public String getSname() {
        return this.sname;
    }
    
    public void setSname(String sname) {
        this.sname = sname;
    }
    public String getSgender() {
        return this.sgender;
    }
    
    public void setSgender(String sgender) {
        this.sgender = sgender;
    }
    public String getSphone() {
        return this.sphone;
    }
    
    public void setSphone(String sphone) {
        this.sphone = sphone;
    }
    public String getSemail() {
        return this.semail;
    }
    
    public void setSemail(String semail) {
        this.semail = semail;
    }




}


